v1.2
NoQuea/SauceDemo2 pull request #1
Opened 2021-11-29 21:00 UTC by NoQuea

2021-11-29 21:14 UTC, mikola-2 requested changes

2021-11-29 21:14 UTC, mikola-2 commented on pom.xml
> +        <dependency>
Не понятно зачем. Я удалил зависимость, импорт, вызов и тесты продолжили работать.

2021-11-29 21:14 UTC, mikola-2 commented on pom.xml
> +        <dependency>
Вторая зависимость с тестЭнДжи. Первая чуть выше. Удаляй.

2021-11-29 21:14 UTC, mikola-2 commented on src/test/java/tests/BaseTest.java
> +        BasicConfigurator.configure();
Всё та же непонятная хрень. Без неё работает.

2021-11-29 21:14 UTC, mikola-2 commented on src/test/java/tests/BaseTest.java
> +        Thread.sleep(1500);
Зачем это тут?

2021-11-29 21:14 UTC, mikola-2 commented on src/test/java/tests/BaseTest.java
> +    @Test
Метод, отмеченный аннотацией @Тест в базовом классе теста. Лучше перенеси его в LoginPage и вызывай оттуда.

2021-11-29 21:14 UTC, mikola-2 commented on src/test/java/tests/CartTest.java
> +        loginToTheSystem();
Тест без проверок, это не тест.

2021-11-29 21:14 UTC, mikola-2 commented on src/test/java/tests/ProductsCriticalPathTest.java
> +    public void productShouldAddedIntoCart(){
Тест без проверок ничего не проверяет.

2021-11-30 14:06 UTC, NoQuea commented on pom.xml
> +        <dependency>
![image](https://user-images.githubusercontent.com/90712546/144061868-884ba085-cc56-44fb-994c-9b23720155d3.png)
вот так вся зависимость выглядит то есть это же зависимотсь bonigarcia

2021-11-30 14:11 UTC, NoQuea commented on pom.xml
> +        <dependency>
![image](https://user-images.githubusercontent.com/90712546/144062606-73ca24cc-47b0-4aa0-abf0-a30e2f551615.png)
вот в чем ошибка заключается и вот почему я добавил
![image](https://user-images.githubusercontent.com/90712546/144062758-036a09f3-bd8a-42d4-b34d-013ff2b73c6f.png)

2021-11-30 14:37 UTC, NoQuea commented on src/test/java/tests/BaseTest.java
> +        Thread.sleep(1500);
Для того чтобы он сразу не выключался и я мог увидеть результат

2021-11-30 14:38 UTC, NoQuea commented on src/test/java/tests/BaseTest.java
> +        BasicConfigurator.configure();
У меня выпадает ошибка log4j

2021-11-30 15:34 UTC, mikola-2 commented on src/test/java/tests/BaseTest.java
> +        Thread.sleep(1500);
Хитро) Можно точку останова ставить.

2021-11-30 15:35 UTC, mikola-2 approved these changes

2022-01-11 13:45 UTC, mikola-2 approved these changes

2022-01-11 14:26 UTC, mikola-2 approved these changes

2022-01-14 17:14 UTC, merged